### ISSUE TITLE
Wrong type for function

### ISSUE THREAD

**Issue by caffeinepills** [mrJean1/PyCocoa#5]
```py
from pycocoa import *

app = NSApplication.sharedApplication()

app.nextEventMatchingMask_untilDate_inMode_dequeue_(NSAnyEventMask, NSDate.distantPast(), NSDefaultRunLoopMode, YES)
```

This should be a valid call, but the types don't work. 
https://developer.apple.com/documentation/appkit/nsapplication/1428485-nexteventmatchingmask

Produces error:
```py
ctypes.ArgumentError: argument 5: TypeError: wrong type: NSApplication.nextEventMatchingMask_untilDate_inMode_dequeue_(Id_t, SEL_t, c_ulong, Id_t, Id_t, c_byte) Id_t
```

EDIT: This resolves the issue: 
```py
        loop = ctypes.cast(NSDefaultRunLoopMode, ctypes.POINTER(Id_t))
        event = NSApp.nextEventMatchingMask_untilDate_inMode_dequeue_(
            NSAnyEventMask, timeout_date, loop, True)
```

However, the type should work without having to re-cast it.

**Comment by mrJean1** [comment]
Thank you for reporting.  The `type(NSDefaultRunLoopMode)` has been corrected in [PyCocoa 23.02.05](https://pypi.org/project/PyCocoa/) and later.
